services:
  postgres:
    image: ankane/pgvector:latest
    container_name: postgres_genai
    environment:
      POSTGRES_DB: gen_ai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data_local:/var/lib/postgresql/data